/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

// The frontend needs the public project ID and anon key.  You can set
// these via Vite environment variables (see .env.example) or leave the
// hardcoded defaults below for the original demo project.

export const projectId =
  import.meta.env.VITE_SUPABASE_PROJECT_ID ||
  "owmyjtkslqphuyjibrbx";
export const publicAnonKey =
  import.meta.env.VITE_SUPABASE_ANON_KEY ||
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im93bXlqdGtzbHFwaHV5amlicmJ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzIwNjQ4MDUsImV4cCI6MjA4NzY0MDgwNX0.GRSJBAuAbiSlBfqmMxinlcjf2S3Gl0ABMk-TM_DOI5s";